// <auto-generated />
namespace ForcaDaIlha3.Repositorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adicionartabelapontuacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicionartabelapontuacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201611131641325_adicionar tabela pontuacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
